name: wetbulb-potential
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - requests
  - pyyaml
  - pydantic
  - psychrolib
  - timezonefinder
  - tzdata
  - pytest
  - ruff
  - pip
  - pip:
      - dash
      - plotly
